const contentSchema = [
  {
    id: 'global',
    title: 'Global',
    fields: [
      { key: 'global.back_label', label: 'Back Link Label', type: 'text', default: 'Back to Home' },
      { key: 'global.status.loading', label: 'Status Loading Label', type: 'text', default: 'Loading...' },
      { key: 'global.status.open_label', label: 'Status Open Label', type: 'text', default: 'Open' },
      { key: 'global.status.closed_label', label: 'Status Closed Label', type: 'text', default: 'Closed' },
      { key: 'global.status.open_until_label', label: 'Status Open Until Label', type: 'text', default: 'til' },
      { key: 'global.status.hours_unavailable', label: 'Status Hours Unavailable', type: 'text', default: 'Hours unavailable' },
      { key: 'global.days.0', label: 'Day Label Sunday', type: 'text', default: 'Sunday' },
      { key: 'global.days.1', label: 'Day Label Monday', type: 'text', default: 'Monday' },
      { key: 'global.days.2', label: 'Day Label Tuesday', type: 'text', default: 'Tuesday' },
      { key: 'global.days.3', label: 'Day Label Wednesday', type: 'text', default: 'Wednesday' },
      { key: 'global.days.4', label: 'Day Label Thursday', type: 'text', default: 'Thursday' },
      { key: 'global.days.5', label: 'Day Label Friday', type: 'text', default: 'Friday' },
      { key: 'global.days.6', label: 'Day Label Saturday', type: 'text', default: 'Saturday' },
    ],
  },
  {
    id: 'nav',
    title: 'Navigation',
    fields: [
      { key: 'nav.logo_src', label: 'Logo Image', type: 'image', default: '/images/logos/blvd-park-logo.webp' },
      { key: 'nav.logo_alt', label: 'Logo Alt Text', type: 'text', default: 'BLVD Park' },
      { key: 'nav.links.0.label', label: 'Nav Link 1 Label', type: 'text', default: 'Menu' },
      { key: 'nav.links.0.href', label: 'Nav Link 1 URL', type: 'url', default: '/menu' },
      { key: 'nav.links.1.label', label: 'Nav Link 2 Label', type: 'text', default: 'Pickleball' },
      { key: 'nav.links.1.href', label: 'Nav Link 2 URL', type: 'url', default: '/#pickleball' },
      { key: 'nav.links.2.label', label: 'Nav Link 3 Label', type: 'text', default: 'Events' },
      { key: 'nav.links.2.href', label: 'Nav Link 3 URL', type: 'url', default: '/#events' },
      { key: 'nav.links.3.label', label: 'Nav Link 4 Label', type: 'text', default: 'Hours' },
      { key: 'nav.links.3.href', label: 'Nav Link 4 URL', type: 'url', default: '/#hours-location' },
      { key: 'nav.cta.label', label: 'Nav CTA Label', type: 'text', default: 'Reserve' },
      { key: 'nav.cta.href', label: 'Nav CTA URL', type: 'url', default: '/book' },
      { key: 'nav.mobile.location', label: 'Mobile Footer Location', type: 'text', default: 'The Heights · Houston, TX' },
    ],
  },
  {
    id: 'social',
    title: 'Social Links',
    fields: [
      { key: 'social.instagram', label: 'Instagram URL', type: 'url', default: 'https://instagram.com/blvdparkhtx' },
      { key: 'social.facebook', label: 'Facebook URL', type: 'url', default: 'https://facebook.com/blvdparkhtx' },
    ],
  },
  {
    id: 'home.hero',
    title: 'Home - Hero',
    fields: [
      { key: 'home.hero.location', label: 'Location Eyebrow', type: 'text', default: 'Houston, TX' },
      { key: 'home.hero.headline_top', label: 'Headline (Top Line)', type: 'text', default: "The Heights'" },
      { key: 'home.hero.headline_highlight', label: 'Headline (Highlight)', type: 'text', default: 'PLAYGROUND' },
      {
        key: 'home.hero.tagline_html',
        label: 'Tagline (HTML)',
        type: 'rich',
        default: '<span class="text-[#C9A962]">Sports</span> · <span class="text-white/70">Social</span> · <span class="text-[#C9A962]">Scene</span>',
      },
      { key: 'home.hero.cta_primary.label', label: 'Primary CTA Label', type: 'text', default: 'Events' },
      { key: 'home.hero.cta_primary.href', label: 'Primary CTA URL', type: 'url', default: '/#events' },
      { key: 'home.hero.cta_secondary.label', label: 'Secondary CTA Label', type: 'text', default: 'Menu' },
      { key: 'home.hero.cta_secondary.href', label: 'Secondary CTA URL', type: 'url', default: '/menu' },
      { key: 'home.hero.info_location', label: 'Info Bar Location', type: 'text', default: 'Heights, HTX' },
      { key: 'home.hero.video_src', label: 'Hero Video Source', type: 'image', default: '/images/blvdhero.mp4' },
      { key: 'home.hero.poster_src', label: 'Hero Poster Image', type: 'image', default: '/images/venue/venue-hero-tall.webp' },
      { key: 'home.hero.fallback_src', label: 'Hero Fallback Image', type: 'image', default: '/images/venue/venue-hero-tall.webp' },
    ],
  },
  {
    id: 'home.value_props',
    title: 'Home - Value Props',
    fields: [
      { key: 'home.value_props.0.label', label: 'Value Prop 1', type: 'text', default: 'FREE PICKLEBALL' },
      { key: 'home.value_props.1.label', label: 'Value Prop 2', type: 'text', default: 'CRAFT BAR' },
      { key: 'home.value_props.2.label', label: 'Value Prop 3', type: 'text', default: '50+ SCREENS' },
      { key: 'home.value_props.3.label', label: 'Value Prop 4', type: 'text', default: 'OPEN LATE' },
    ],
  },
  {
    id: 'home.specials',
    title: 'Home - Daily Specials',
    fields: [
      { key: 'home.specials.eyebrow', label: 'Section Eyebrow', type: 'text', default: 'Daily Specials' },
      {
        key: 'home.specials.headline_html',
        label: 'Section Headline (HTML)',
        type: 'rich',
        default: 'The week plays differently<br class="hidden sm:block"/> at BLVD Park.',
      },
      {
        key: 'home.specials.subtext',
        label: 'Section Subtext',
        type: 'textarea',
        default: 'Apps, burgers, wings, and buckets stacked from Monday through Sunday. Pick your day, grab your crew.',
      },
      { key: 'home.specials.0.day', label: 'Special 1 Day', type: 'text', default: 'Monday' },
      { key: 'home.specials.0.tag', label: 'Special 1 Tag', type: 'text', default: 'Happy Hour' },
      { key: 'home.specials.0.items', label: 'Special 1 Items (one per line)', type: 'textarea', default: '1/2 off apps all day\n$5 domestics' },
      { key: 'home.specials.0.featured', label: 'Special 1 Featured', type: 'boolean', default: false },

      { key: 'home.specials.1.day', label: 'Special 2 Day', type: 'text', default: 'Tuesday' },
      { key: 'home.specials.1.tag', label: 'Special 2 Tag', type: 'text', default: 'Burger Night' },
      { key: 'home.specials.1.items', label: 'Special 2 Items (one per line)', type: 'textarea', default: '$10 cheeseburger with fries and domestic beer' },
      { key: 'home.specials.1.featured', label: 'Special 2 Featured', type: 'boolean', default: false },

      { key: 'home.specials.2.day', label: 'Special 3 Day', type: 'text', default: 'Wednesday' },
      { key: 'home.specials.2.tag', label: 'Special 3 Tag', type: 'text', default: 'Wing Wednesday' },
      { key: 'home.specials.2.items', label: 'Special 3 Items (one per line)', type: 'textarea', default: '$1 wings\n$5 shots' },
      { key: 'home.specials.2.featured', label: 'Special 3 Featured', type: 'boolean', default: false },

      { key: 'home.specials.3.day', label: 'Special 4 Day', type: 'text', default: 'Thursday' },
      { key: 'home.specials.3.tag', label: 'Special 4 Tag', type: 'text', default: 'Burger & Tequila' },
      { key: 'home.specials.3.items', label: 'Special 4 Items (one per line)', type: 'textarea', default: '$12 burgers and sandwiches\n$6 tequila shots' },
      { key: 'home.specials.3.featured', label: 'Special 4 Featured', type: 'boolean', default: false },

      { key: 'home.specials.4.day', label: 'Special 5 Day', type: 'text', default: 'Friday' },
      { key: 'home.specials.4.tag', label: 'Special 5 Tag', type: 'text', default: 'TGIF Deals' },
      { key: 'home.specials.4.items', label: 'Special 5 Items (one per line)', type: 'textarea', default: '1/2 off wraps\n1/2 off espresso martinis' },
      { key: 'home.specials.4.featured', label: 'Special 5 Featured', type: 'boolean', default: false },

      { key: 'home.specials.5.day', label: 'Special 6 Day', type: 'text', default: 'Weekend' },
      { key: 'home.specials.5.tag', label: 'Special 6 Tag', type: 'text', default: 'Saturday & Sunday' },
      {
        key: 'home.specials.5.items',
        label: 'Special 6 Items (one per line)',
        type: 'textarea',
        default: '$1 boneless wings\n$20 domestic buckets\n$25 import buckets\n$30 seltzer buckets\n$5 shots',
      },
      { key: 'home.specials.5.featured', label: 'Special 6 Featured', type: 'boolean', default: true },
    ],
  },
  {
    id: 'home.about',
    title: 'Home - About',
    fields: [
      { key: 'home.about.eyebrow', label: 'Eyebrow', type: 'text', default: 'About Us' },
      { key: 'home.about.headline_line1', label: 'Headline Line 1', type: 'text', default: 'Where Houston' },
      { key: 'home.about.headline_line2', label: 'Headline Line 2', type: 'text', default: 'Comes to Play' },
      {
        key: 'home.about.body_html',
        label: 'Body (HTML)',
        type: 'rich',
        default:
          '<p>Part sports bar, part social club, part neighborhood living room. BLVD Park is where the Heights comes when they want to watch the game, grab a drink, or just be around good energy.</p><p>Free pickleball, a bar that actually knows what it’s doing, and enough TVs that you’ll never miss a play. Come solo or bring the crew.</p>',
      },
      { key: 'home.about.image_primary_src', label: 'Primary Image', type: 'image', default: '/images/2026GALLERY/DSC03577.jpg' },
      { key: 'home.about.image_primary_alt', label: 'Primary Image Alt', type: 'text', default: 'BLVD Park Atmosphere' },
      { key: 'home.about.card_title', label: 'Card Title', type: 'text', default: 'The Heights' },
      { key: 'home.about.card_subtitle', label: 'Card Subtitle', type: 'text', default: 'Houston, TX' },
      { key: 'home.about.card_image_src', label: 'Card Image', type: 'image', default: '/images/2026GALLERY/DSC01726.jpg' },
      { key: 'home.about.card_image_alt', label: 'Card Image Alt', type: 'text', default: 'BLVD Park' },
      { key: 'home.about.stats.0.value', label: 'Stat 1 Value', type: 'text', default: 'FREE' },
      { key: 'home.about.stats.0.label', label: 'Stat 1 Label', type: 'text', default: 'Pickleball' },
      { key: 'home.about.stats.1.value', label: 'Stat 2 Value', type: 'text', default: '50+' },
      { key: 'home.about.stats.1.label', label: 'Stat 2 Label', type: 'text', default: 'HD Screens' },
      { key: 'home.about.stats.2.value', label: 'Stat 3 Value', type: 'text', default: '7' },
      { key: 'home.about.stats.2.label', label: 'Stat 3 Label', type: 'text', default: 'Days/Week' },
      { key: 'home.about.cta.label', label: 'CTA Label', type: 'text', default: 'Book an Event' },
      { key: 'home.about.cta.href', label: 'CTA URL', type: 'url', default: '/book' },
    ],
  },
  {
    id: 'home.gallery',
    title: 'Home - Gallery',
    fields: [
      { key: 'home.gallery.handle', label: 'Handle', type: 'text', default: '@blvdparkhtx' },
      {
        key: 'home.gallery.headline_html',
        label: 'Headline (HTML)',
        type: 'rich',
        default: 'It\'s a <span class="text-blvd-green-bright">BLVD</span> Thing',
      },
      { key: 'home.gallery.status_loading', label: 'Loading Status', type: 'text', default: 'Loading gallery...' },
      { key: 'home.gallery.status_unavailable', label: 'Unavailable Status', type: 'text', default: 'Gallery unavailable.' },
      { key: 'home.gallery.cta.label', label: 'CTA Label', type: 'text', default: 'Follow @blvdparkhtx' },
      { key: 'home.gallery.cta.href', label: 'CTA URL', type: 'url', default: 'https://instagram.com/blvdparkhtx' },
    ],
  },
  {
    id: 'home.events',
    title: 'Home - Events Section',
    fields: [
      { key: 'home.events.eyebrow', label: 'Eyebrow', type: 'text', default: "What's Happening" },
      { key: 'home.events.headline', label: 'Headline', type: 'text', default: 'BLVD Events' },
      { key: 'home.events.loading_label', label: 'Loading Label', type: 'text', default: 'Loading events...' },
      { key: 'home.events.featured_title_fallback', label: 'Featured Title Fallback', type: 'text', default: 'Upcoming Events' },
      { key: 'home.events.featured_description_fallback', label: 'Featured Description Fallback', type: 'textarea', default: 'Check back soon for the latest events and specials.' },
      { key: 'home.events.featured_cta.label', label: 'Featured CTA Label', type: 'text', default: 'Reserve Your Spot' },
      { key: 'home.events.featured_cta.href', label: 'Featured CTA URL', type: 'url', default: '/book' },
      { key: 'home.events.item_cta.label', label: 'Event Item CTA Label', type: 'text', default: 'Reserve a Table' },
      { key: 'home.events.item_cta.href', label: 'Event Item CTA URL', type: 'url', default: '/book' },
      { key: 'home.events.cta.label', label: 'CTA Label', type: 'text', default: 'Book Your Event' },
      { key: 'home.events.cta.href', label: 'CTA URL', type: 'url', default: '/book' },
      { key: 'home.events.featured_label', label: 'Featured Badge Label', type: 'text', default: 'FEATURED' },
    ],
  },
  {
    id: 'home.menu_section',
    title: 'Home - Menu Section',
    fields: [
      { key: 'home.menu.eyebrow', label: 'Eyebrow', type: 'text', default: 'Food & Cocktails' },
      {
        key: 'home.menu.headline_html',
        label: 'Headline (HTML)',
        type: 'rich',
        default: 'Eat & Drink at <span class="text-blvd-green-bright">BLVD</span>',
      },
      {
        key: 'home.menu.subtext',
        label: 'Subtext',
        type: 'textarea',
        default: 'Chef-driven bites and craft cocktails. Perfect for pre-game fuel or post-match celebrations.',
      },
      { key: 'home.menu.cta_primary.label', label: 'Primary CTA Label', type: 'text', default: 'Main Menu' },
      { key: 'home.menu.cta_primary.href', label: 'Primary CTA URL', type: 'url', default: '/menu' },
      { key: 'home.menu.cta_secondary.label', label: 'Secondary CTA Label', type: 'text', default: 'Lunch Menu' },
      { key: 'home.menu.cta_secondary.href', label: 'Secondary CTA URL', type: 'url', default: '/menu/lunch' },

      { key: 'home.menu.grid.0.image', label: 'Grid 1 Image', type: 'image', default: '/images/drinks/drinks-craft.webp' },
      { key: 'home.menu.grid.0.alt', label: 'Grid 1 Alt', type: 'text', default: 'BLVD Craft Cocktails' },
      { key: 'home.menu.grid.0.eyebrow', label: 'Grid 1 Eyebrow', type: 'text', default: 'Signature' },
      { key: 'home.menu.grid.0.label', label: 'Grid 1 Label', type: 'text', default: 'Craft Cocktails' },

      { key: 'home.menu.grid.1.image', label: 'Grid 2 Image', type: 'image', default: '/images/food/food-appetizer.webp' },
      { key: 'home.menu.grid.1.alt', label: 'Grid 2 Alt', type: 'text', default: 'BLVD Appetizers' },
      { key: 'home.menu.grid.1.label', label: 'Grid 2 Label', type: 'text', default: 'Starters' },

      { key: 'home.menu.grid.2.image', label: 'Grid 3 Image', type: 'image', default: '/images/food/food-popular.webp' },
      { key: 'home.menu.grid.2.alt', label: 'Grid 3 Alt', type: 'text', default: 'BLVD Sliders' },
      { key: 'home.menu.grid.2.label', label: 'Grid 3 Label', type: 'text', default: 'Sliders' },

      { key: 'home.menu.grid.3.image', label: 'Grid 4 Image', type: 'image', default: '/images/food/food-gourmet.webp' },
      { key: 'home.menu.grid.3.alt', label: 'Grid 4 Alt', type: 'text', default: 'BLVD Gourmet' },
      { key: 'home.menu.grid.3.label', label: 'Grid 4 Label', type: 'text', default: 'Tacos' },

      { key: 'home.menu.grid.4.image', label: 'Grid 5 Image', type: 'image', default: '/images/drinks/drinks-beverage.webp' },
      { key: 'home.menu.grid.4.alt', label: 'Grid 5 Alt', type: 'text', default: 'BLVD Beverages' },
      { key: 'home.menu.grid.4.label', label: 'Grid 5 Label', type: 'text', default: 'Bloody Marys' },

      { key: 'home.menu.grid.5.image', label: 'Grid 6 Image', type: 'image', default: '/images/food/food-main-course.webp' },
      { key: 'home.menu.grid.5.alt', label: 'Grid 6 Alt', type: 'text', default: 'BLVD Signature Burgers' },
      { key: 'home.menu.grid.5.eyebrow', label: 'Grid 6 Eyebrow', type: 'text', default: 'Fan Favorite' },
      { key: 'home.menu.grid.5.label', label: 'Grid 6 Label', type: 'text', default: 'Signature Burgers' },

      { key: 'home.menu.grid.6.image', label: 'Grid 7 Image', type: 'image', default: '/images/food/food-chef-special.webp' },
      { key: 'home.menu.grid.6.alt', label: 'Grid 7 Alt', type: 'text', default: 'Chef Specials' },
      { key: 'home.menu.grid.6.label', label: 'Grid 7 Label', type: 'text', default: 'Specials' },

      { key: 'home.menu.grid.7.image', label: 'Grid 8 Image', type: 'image', default: '/images/drinks/drinks-cocktail.webp' },
      { key: 'home.menu.grid.7.alt', label: 'Grid 8 Alt', type: 'text', default: 'BLVD Cocktails' },
      { key: 'home.menu.grid.7.label', label: 'Grid 8 Label', type: 'text', default: 'Mules' },
    ],
  },
  {
    id: 'home.vibe',
    title: 'Home - Vibe Section',
    fields: [
      { key: 'home.vibe.eyebrow', label: 'Eyebrow', type: 'text', default: 'The Vibe' },
      { key: 'home.vibe.headline', label: 'Headline', type: 'text', default: 'Your Kind of Night' },
      {
        key: 'home.vibe.subtext',
        label: 'Subtext',
        type: 'textarea',
        default: "Whether you're here for the game, the drinks, or the company—we've got a spot for you.",
      },
      { key: 'home.vibe.stats.0.value', label: 'Stat 1 Value', type: 'text', default: '4.8' },
      { key: 'home.vibe.stats.0.suffix', label: 'Stat 1 Suffix', type: 'text', default: '★' },
      { key: 'home.vibe.stats.0.label', label: 'Stat 1 Label', type: 'text', default: 'Google Rating' },
      { key: 'home.vibe.stats.1.value', label: 'Stat 2 Value', type: 'text', default: '50+' },
      { key: 'home.vibe.stats.1.suffix', label: 'Stat 2 Suffix', type: 'text', default: '' },
      { key: 'home.vibe.stats.1.label', label: 'Stat 2 Label', type: 'text', default: 'Screens' },
      { key: 'home.vibe.stats.2.value', label: 'Stat 3 Value', type: 'text', default: '4' },
      { key: 'home.vibe.stats.2.suffix', label: 'Stat 3 Suffix', type: 'text', default: '' },
      { key: 'home.vibe.stats.2.label', label: 'Stat 3 Label', type: 'text', default: 'Courts' },
      { key: 'home.vibe.stats.3.value', label: 'Stat 4 Value', type: 'text', default: '2am' },
      { key: 'home.vibe.stats.3.suffix', label: 'Stat 4 Suffix', type: 'text', default: '' },
      { key: 'home.vibe.stats.3.label', label: 'Stat 4 Label', type: 'text', default: 'Open Late' },

      { key: 'home.vibe.cards.0.title', label: 'Vibe Card 1 Title', type: 'text', default: 'Date Night' },
      {
        key: 'home.vibe.cards.0.description',
        label: 'Vibe Card 1 Description',
        type: 'textarea',
        default: 'Craft cocktails, mood lighting, and enough games to break the ice without trying too hard.',
      },
      { key: 'home.vibe.cards.1.title', label: 'Vibe Card 2 Title', type: 'text', default: 'Game Day HQ' },
      {
        key: 'home.vibe.cards.1.description',
        label: 'Vibe Card 2 Description',
        type: 'textarea',
        default: 'Every seat’s a good seat. 50+ screens, sound on for the big games, and a crowd that actually cares.',
      },
      { key: 'home.vibe.cards.2.title', label: 'Vibe Card 3 Title', type: 'text', default: 'Late Night' },
      {
        key: 'home.vibe.cards.2.description',
        label: 'Vibe Card 3 Description',
        type: 'textarea',
        default: 'When everywhere else closes. Strong pours, late night bites, and the stories that come with them.',
      },

      { key: 'home.vibe.quote', label: 'Quote', type: 'textarea', default: '"Best spot in the Heights. Period. Come for the games, stay for the vibes."' },
      { key: 'home.vibe.cite_name', label: 'Quote Source', type: 'text', default: 'Google Review' },
      { key: 'home.vibe.cite_rating', label: 'Quote Rating', type: 'text', default: '★★★★★' },
    ],
  },
  {
    id: 'home.pickleball',
    title: 'Home - Pickleball',
    fields: [
      { key: 'home.pickleball.eyebrow', label: 'Eyebrow', type: 'text', default: 'Courts Open Daily' },
      { key: 'home.pickleball.headline_line1', label: 'Headline Line 1', type: 'text', default: 'Pickleball in' },
      { key: 'home.pickleball.headline_line2', label: 'Headline Line 2', type: 'text', default: 'The Heights' },
      {
        key: 'home.pickleball.description',
        label: 'Description',
        type: 'textarea',
        default: 'Our courts are open daily and always free — no reservations, no memberships, no gatekeeping. Paddle in one hand, drink in the other.',
      },
      { key: 'home.pickleball.hours.0.label', label: 'Hours 1 Label', type: 'text', default: 'Mon-Tue' },
      { key: 'home.pickleball.hours.0.value', label: 'Hours 1 Value', type: 'text', default: '4PM-12AM' },
      { key: 'home.pickleball.hours.1.label', label: 'Hours 2 Label', type: 'text', default: 'Wed-Thu' },
      { key: 'home.pickleball.hours.1.value', label: 'Hours 2 Value', type: 'text', default: '12PM-12AM' },
      { key: 'home.pickleball.hours.2.label', label: 'Hours 3 Label', type: 'text', default: 'Friday' },
      { key: 'home.pickleball.hours.2.value', label: 'Hours 3 Value', type: 'text', default: '12PM-2AM' },
      { key: 'home.pickleball.hours.3.label', label: 'Hours 4 Label', type: 'text', default: 'Saturday' },
      { key: 'home.pickleball.hours.3.value', label: 'Hours 4 Value', type: 'text', default: '11AM-2AM' },
      { key: 'home.pickleball.hours.4.label', label: 'Hours 5 Label', type: 'text', default: 'Sunday' },
      { key: 'home.pickleball.hours.4.value', label: 'Hours 5 Value', type: 'text', default: '12PM-12AM' },
      { key: 'home.pickleball.cta.label', label: 'CTA Label', type: 'text', default: 'Get Directions' },
      {
        key: 'home.pickleball.cta.href',
        label: 'CTA URL',
        type: 'url',
        default: 'https://maps.google.com/?q=1119+W+20th+St,+Houston,+TX+77008',
      },
      { key: 'home.pickleball.background_src', label: 'Background Image', type: 'image', default: '/images/pickleballhome.jpg' },
      { key: 'home.pickleball.background_alt', label: 'Background Image Alt', type: 'text', default: 'Pickleball at BLVD Park' },
      { key: 'home.pickleball.badge_top', label: 'Badge Top Text', type: 'text', default: 'FREE' },
      { key: 'home.pickleball.badge_bottom', label: 'Badge Bottom Text', type: 'text', default: 'Pickleball' },
    ],
  },
  {
    id: 'home.location',
    title: 'Home - Location',
    fields: [
      { key: 'home.location.eyebrow', label: 'Eyebrow', type: 'text', default: 'Find Us' },
      { key: 'home.location.headline', label: 'Headline', type: 'text', default: 'Hours & Location' },
      { key: 'home.location.subtext', label: 'Subtext', type: 'textarea', default: 'In the heart of The Heights, Houston' },
      { key: 'home.location.hours_title', label: 'Hours Card Title', type: 'text', default: 'Hours' },
      { key: 'home.location.address_title', label: 'Address Card Title', type: 'text', default: 'Location' },
      { key: 'home.location.address_line1', label: 'Address Line 1', type: 'text', default: '1119 W 20th Street' },
      { key: 'home.location.address_line2', label: 'Address Line 2', type: 'text', default: 'Houston, TX 77008' },
      { key: 'home.location.address_note', label: 'Address Note', type: 'text', default: 'The Heights • Free parking available' },
      { key: 'home.location.directions_label', label: 'Directions Label', type: 'text', default: 'Get Directions' },
      {
        key: 'home.location.directions_href',
        label: 'Directions URL',
        type: 'url',
        default: 'https://maps.google.com/?q=1119+W+20th+St,+Houston,+TX+77008',
      },
      { key: 'home.location.connect_title', label: 'Connect Card Title', type: 'text', default: 'Connect' },
      {
        key: 'home.location.map_embed_url',
        label: 'Map Embed URL',
        type: 'url',
        default:
          'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3462.6384254673!2d-95.41513548488878!3d29.805361381970723!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8640c70c3a6b30d5%3A0x9c8c8c6c8c8c8c8c!2s1119%20W%2020th%20St%2C%20Houston%2C%20TX%2077008!5e0!3m2!1sen!2sus!4v1234567890',
      },
      { key: 'home.location.follow_label', label: 'Follow Us Label', type: 'text', default: 'Follow Us' },
    ],
  },
  {
    id: 'footer',
    title: 'Footer',
    fields: [
      { key: 'footer.brand', label: 'Brand Name', type: 'text', default: 'BLVD PARK' },
      {
        key: 'footer.about',
        label: 'About Text',
        type: 'textarea',
        default:
          'Sports bar meets social club. Free pickleball, 50+ screens, craft cocktails, and the kind of crowd that makes any night worth staying out for.',
      },
      { key: 'footer.explore_title', label: 'Explore Title', type: 'text', default: 'Explore' },
      { key: 'footer.explore_links.0.label', label: 'Explore Link 1 Label', type: 'text', default: 'Menu' },
      { key: 'footer.explore_links.0.href', label: 'Explore Link 1 URL', type: 'url', default: '/menu' },
      { key: 'footer.explore_links.1.label', label: 'Explore Link 2 Label', type: 'text', default: 'Pickleball' },
      { key: 'footer.explore_links.1.href', label: 'Explore Link 2 URL', type: 'url', default: '/#pickleball' },
      { key: 'footer.explore_links.2.label', label: 'Explore Link 3 Label', type: 'text', default: 'Events' },
      { key: 'footer.explore_links.2.href', label: 'Explore Link 3 URL', type: 'url', default: '/#events' },
      { key: 'footer.explore_links.3.label', label: 'Explore Link 4 Label', type: 'text', default: 'Hours & Location' },
      { key: 'footer.explore_links.3.href', label: 'Explore Link 4 URL', type: 'url', default: '/#hours-location' },
      { key: 'footer.explore_links.4.label', label: 'Explore Link 5 Label', type: 'text', default: 'Reserve a Table' },
      { key: 'footer.explore_links.4.href', label: 'Explore Link 5 URL', type: 'url', default: '/book' },
      { key: 'footer.hours_title', label: 'Hours Title', type: 'text', default: 'Hours' },
      { key: 'footer.hours.0.label', label: 'Footer Hours 1 Label', type: 'text', default: 'Mon – Tue' },
      { key: 'footer.hours.0.value', label: 'Footer Hours 1 Value', type: 'text', default: '4PM – 12AM' },
      { key: 'footer.hours.1.label', label: 'Footer Hours 2 Label', type: 'text', default: 'Wed – Thu' },
      { key: 'footer.hours.1.value', label: 'Footer Hours 2 Value', type: 'text', default: '12PM – 12AM' },
      { key: 'footer.hours.2.label', label: 'Footer Hours 3 Label', type: 'text', default: 'Friday' },
      { key: 'footer.hours.2.value', label: 'Footer Hours 3 Value', type: 'text', default: '12PM – 2AM' },
      { key: 'footer.hours.3.label', label: 'Footer Hours 4 Label', type: 'text', default: 'Saturday' },
      { key: 'footer.hours.3.value', label: 'Footer Hours 4 Value', type: 'text', default: '11AM – 2AM' },
      { key: 'footer.hours.4.label', label: 'Footer Hours 5 Label', type: 'text', default: 'Sunday' },
      { key: 'footer.hours.4.value', label: 'Footer Hours 5 Value', type: 'text', default: '12PM – 12AM' },
      { key: 'footer.visit_title', label: 'Visit Title', type: 'text', default: 'Visit Us' },
      { key: 'footer.address_line1', label: 'Footer Address Line 1', type: 'text', default: '1119 W 20th Street' },
      { key: 'footer.address_line2', label: 'Footer Address Line 2', type: 'text', default: 'Houston, TX 77008' },
      { key: 'footer.directions_label', label: 'Directions Label', type: 'text', default: 'Get Directions' },
      { key: 'footer.privacy_href', label: 'Privacy Link URL', type: 'url', default: '/privacy' },
      { key: 'footer.privacy_label', label: 'Privacy Link Label', type: 'text', default: 'Privacy Policy' },
      { key: 'footer.terms_href', label: 'Terms Link URL', type: 'url', default: '/terms' },
      { key: 'footer.terms_label', label: 'Terms Link Label', type: 'text', default: 'Terms of Service' },
      {
        key: 'footer.copyright_html',
        label: 'Copyright (HTML)',
        type: 'rich',
        default: '© {year} BLVD Park. All rights reserved.',
      },
    ],
  },
  {
    id: 'home.superbowl',
    title: 'Home - Super Bowl Modal',
    fields: [
      { key: 'home.superbowl.enabled', label: 'Modal Enabled', type: 'boolean', default: true },
      { key: 'home.superbowl.image_src', label: 'Modal Image', type: 'image', default: '/images/events/superbowl16.webp' },
      {
        key: 'home.superbowl.image_alt',
        label: 'Modal Image Alt',
        type: 'text',
        default: 'Super Bowl at BLVD Park - February 9, Sunday Funday in The Heights Houston',
      },
      { key: 'home.superbowl.cta_label', label: 'Modal CTA Label', type: 'text', default: 'Reserve Your Table' },
      { key: 'home.superbowl.cta_href', label: 'Modal CTA URL', type: 'url', default: '/book' },
    ],
  },
  {
    id: 'menu.main',
    title: 'Menu Page - Main',
    fields: [
      { key: 'menu.main.eyebrow', label: 'Eyebrow', type: 'text', default: 'Food & Drink' },
      { key: 'menu.main.title', label: 'Title', type: 'text', default: 'The Menu' },
      {
        key: 'menu.main.subtext',
        label: 'Subtext',
        type: 'textarea',
        default: 'Chef-driven bites and craft cocktails. Perfect for pre-game fuel or post-match celebrations.',
      },
      { key: 'menu.main.loading_label', label: 'Loading Label', type: 'text', default: 'Loading menu...' },
      { key: 'menu.main.empty_label', label: 'Empty State Label', type: 'text', default: 'Menu coming soon.' },
      { key: 'menu.main.error_label', label: 'Error Label', type: 'text', default: 'Menu unavailable.' },
      { key: 'menu.main.toggle_main', label: 'Main Toggle Label', type: 'text', default: 'Main Menu' },
      { key: 'menu.main.toggle_lunch', label: 'Lunch Toggle Label', type: 'text', default: 'Lunch Menu' },
      {
        key: 'menu.main.disclaimer',
        label: 'Disclaimer',
        type: 'textarea',
        default: '*Raw or uncooked meats, poultry, seafood or eggs may increase your risk of food-borne illnesses.',
      },
      { key: 'menu.main.cta.title', label: 'CTA Title', type: 'text', default: 'Ready to Join Us?' },
      { key: 'menu.main.cta.subtext', label: 'CTA Subtext', type: 'textarea', default: 'Walk in anytime or reserve a table for your group.' },
      { key: 'menu.main.cta.button_label', label: 'CTA Button Label', type: 'text', default: 'Reserve a Table' },
    ],
  },
  {
    id: 'menu.lunch',
    title: 'Menu Page - Lunch',
    fields: [
      { key: 'menu.lunch.eyebrow', label: 'Eyebrow', type: 'text', default: 'Mon-Fri • 11am-3pm' },
      { key: 'menu.lunch.title', label: 'Title', type: 'text', default: 'Lunch Menu' },
      { key: 'menu.lunch.subtext', label: 'Subtext', type: 'textarea', default: 'Weekday lunch specials. Same quality, friendlier prices.' },
      { key: 'menu.lunch.loading_label', label: 'Loading Label', type: 'text', default: 'Loading menu...' },
      { key: 'menu.lunch.empty_label', label: 'Empty State Label', type: 'text', default: 'Menu coming soon.' },
      { key: 'menu.lunch.error_label', label: 'Error Label', type: 'text', default: 'Menu unavailable.' },
      { key: 'menu.lunch.toggle_main', label: 'Main Toggle Label', type: 'text', default: 'Main Menu' },
      { key: 'menu.lunch.toggle_lunch', label: 'Lunch Toggle Label', type: 'text', default: 'Lunch Menu' },
      {
        key: 'menu.lunch.disclaimer',
        label: 'Disclaimer',
        type: 'textarea',
        default: '*Raw or uncooked meats, poultry, seafood or eggs may increase your risk of food-borne illnesses.',
      },
      { key: 'menu.lunch.cta.title', label: 'CTA Title', type: 'text', default: 'Ready to Join Us?' },
      { key: 'menu.lunch.cta.subtext', label: 'CTA Subtext', type: 'textarea', default: 'Walk in anytime or reserve a table for your group.' },
      { key: 'menu.lunch.cta.button_label', label: 'CTA Button Label', type: 'text', default: 'Reserve a Table' },
    ],
  },
  {
    id: 'menu.notes',
    title: 'Menu Page - Category Notes',
    fields: [
      { key: 'menu.notes.street_tacos', label: 'Street Tacos Note', type: 'text', default: 'Served with three tacos' },
      { key: 'menu.notes.wings', label: 'Wings Note', type: 'text', default: 'Six for twelve • Parmesan ranch or bleu cheese, celery + carrots' },
      { key: 'menu.notes.burgers', label: 'Burgers & Sandwiches Note', type: 'text', default: 'Served with skin-on crispy fries' },
      { key: 'menu.notes.skinny', label: 'The Skinny Note', type: 'text', default: 'Salad, wrap, or rice bowl' },
      { key: 'menu.notes.steak', label: 'Steak Frites Note', type: 'text', default: 'With garlic parmesan fries' },
      { key: 'menu.notes.lunch_street_tacos', label: 'Lunch Street Tacos Note', type: 'text', default: 'Served with three tacos' },
      { key: 'menu.notes.lunch_wings', label: 'Lunch Wings Note', type: 'text', default: 'Six for ten • Parmesan ranch or bleu cheese, celery + carrots' },
      { key: 'menu.notes.lunch_burgers', label: 'Lunch Burgers & Sandwiches Note', type: 'text', default: 'Served with skin-on crispy fries' },
      { key: 'menu.notes.lunch_skinny', label: 'Lunch The Skinny Note', type: 'text', default: 'Salad, wrap, or rice bowl • Add protein: Beef/Shrimp $6, Chicken $5' },
      { key: 'menu.notes.lunch_steak', label: 'Lunch Steak Frites Note', type: 'text', default: 'With garlic parmesan fries' },
    ],
  },
  {
    id: 'book.page',
    title: 'Book Page',
    fields: [
      { key: 'book.hero.eyebrow', label: 'Hero Eyebrow', type: 'text', default: 'Reservations' },
      { key: 'book.hero.title_line1', label: 'Hero Title Line 1', type: 'text', default: 'Reserve Your' },
      { key: 'book.hero.title_line2', label: 'Hero Title Line 2', type: 'text', default: 'Spot' },
      {
        key: 'book.hero.subtext',
        label: 'Hero Subtext',
        type: 'textarea',
        default: "VIP tables, large groups, watch parties. Fill out the form and we’ll get back to you within 24 hours.",
      },
      { key: 'book.hero.image_src', label: 'Hero Image', type: 'image', default: '/images/crowd/crowd-night-1.webp' },
      { key: 'book.hero.image_alt', label: 'Hero Image Alt', type: 'text', default: 'BLVD Park atmosphere' },
      { key: 'book.form.submit_label', label: 'Submit Button Label', type: 'text', default: 'Submit Inquiry' },
      { key: 'book.form.loading_label', label: 'Submit Loading Label', type: 'text', default: 'Sending...' },
      { key: 'book.form.success_title', label: 'Success Title', type: 'text', default: 'Request Received!' },
      { key: 'book.form.success_body', label: 'Success Body', type: 'textarea', default: "We’ll get back to you within 24 hours to confirm your event details." },
      { key: 'book.form.error_text', label: 'Error Text', type: 'textarea', default: 'Something went wrong. Please try again or contact us.' },
      { key: 'book.form.first_name.label', label: 'First Name Label', type: 'text', default: 'First Name *' },
      { key: 'book.form.first_name.placeholder', label: 'First Name Placeholder', type: 'text', default: 'John' },
      { key: 'book.form.last_name.label', label: 'Last Name Label', type: 'text', default: 'Last Name *' },
      { key: 'book.form.last_name.placeholder', label: 'Last Name Placeholder', type: 'text', default: 'Doe' },
      { key: 'book.form.email.label', label: 'Email Label', type: 'text', default: 'Email *' },
      { key: 'book.form.email.placeholder', label: 'Email Placeholder', type: 'text', default: 'john@example.com' },
      { key: 'book.form.phone.label', label: 'Phone Label', type: 'text', default: 'Phone *' },
      { key: 'book.form.phone.placeholder', label: 'Phone Placeholder', type: 'text', default: '(555) 123-4567' },
      { key: 'book.form.date.label', label: 'Date Label', type: 'text', default: 'Date *' },
      { key: 'book.form.time.label', label: 'Time Label', type: 'text', default: 'Preferred Time *' },
      { key: 'book.form.time.placeholder', label: 'Time Placeholder', type: 'text', default: 'Select time' },
      {
        key: 'book.form.time.options',
        label: 'Time Options (one per line)',
        type: 'textarea',
        default: '12:00 PM\n1:00 PM\n2:00 PM\n3:00 PM\n4:00 PM\n5:00 PM\n6:00 PM\n7:00 PM\n8:00 PM\n9:00 PM\n10:00 PM',
      },
      { key: 'book.form.party.label', label: 'Party Size Label', type: 'text', default: 'Party Size *' },
      { key: 'book.form.party.placeholder', label: 'Party Size Placeholder', type: 'text', default: 'Select party size' },
      {
        key: 'book.form.party.options',
        label: 'Party Size Options (value|label per line)',
        type: 'textarea',
        default: '2|2 guests\n4|3-4 guests\n6|5-6 guests\n8|7-8 guests\n10|9-10 guests\n15|11-15 guests\n20|16-20 guests\n30|21-30 guests\n50|31-50 guests\n100|50+ guests',
      },
      { key: 'book.form.message.label', label: 'Message Label', type: 'text', default: 'Tell us about your event' },
      { key: 'book.form.message.placeholder', label: 'Message Placeholder', type: 'text', default: "Birthday, corporate event, watch party... let us know what you're planning" },
      { key: 'book.private.title', label: 'Private Events Title', type: 'text', default: 'Private Events' },
      { key: 'book.private.body', label: 'Private Events Body', type: 'textarea', default: 'Planning a corporate event, birthday, or special occasion?' },
      { key: 'book.private.cta_label', label: 'Private Events CTA Label', type: 'text', default: 'Submit Event Request' },
      { key: 'book.private.cta_href', label: 'Private Events CTA URL', type: 'url', default: 'https://theclegroupllc.tripleseat.com/party_request/42255' },
      { key: 'book.contact.eyebrow', label: 'Contact Eyebrow', type: 'text', default: 'Questions?' },
      { key: 'book.contact.title', label: 'Contact Title', type: 'text', default: 'Get in Touch' },
      { key: 'book.contact.body', label: 'Contact Body', type: 'textarea', default: 'Our team is happy to help with reservations, event planning, or any questions you might have.' },
      { key: 'book.contact.cta_label', label: 'Contact CTA Label', type: 'text', default: 'Contact Us' },
      { key: 'book.contact.cta_href', label: 'Contact CTA URL', type: 'url', default: '/contact' },
      { key: 'book.contact.hours_title', label: 'Contact Hours Title', type: 'text', default: 'Hours' },
      { key: 'book.contact.hours.0.label', label: 'Contact Hours 1 Label', type: 'text', default: 'Mon – Tue' },
      { key: 'book.contact.hours.0.value', label: 'Contact Hours 1 Value', type: 'text', default: '4PM – 12AM' },
      { key: 'book.contact.hours.1.label', label: 'Contact Hours 2 Label', type: 'text', default: 'Wed – Thu' },
      { key: 'book.contact.hours.1.value', label: 'Contact Hours 2 Value', type: 'text', default: '12PM – 12AM' },
      { key: 'book.contact.hours.2.label', label: 'Contact Hours 3 Label', type: 'text', default: 'Friday' },
      { key: 'book.contact.hours.2.value', label: 'Contact Hours 3 Value', type: 'text', default: '12PM – 2AM' },
      { key: 'book.contact.hours.3.label', label: 'Contact Hours 4 Label', type: 'text', default: 'Saturday' },
      { key: 'book.contact.hours.3.value', label: 'Contact Hours 4 Value', type: 'text', default: '11AM – 2AM' },
      { key: 'book.contact.hours.4.label', label: 'Contact Hours 5 Label', type: 'text', default: 'Sunday' },
      { key: 'book.contact.hours.4.value', label: 'Contact Hours 5 Value', type: 'text', default: '12PM – 12AM' },
    ],
  },
  {
    id: 'contact.page',
    title: 'Contact Page',
    fields: [
      { key: 'contact.hero.eyebrow', label: 'Hero Eyebrow', type: 'text', default: 'Contact' },
      { key: 'contact.hero.title', label: 'Hero Title', type: 'text', default: 'Get in Touch' },
      { key: 'contact.hero.subtext', label: 'Hero Subtext', type: 'textarea', default: "Questions? We’d love to hear from you." },
      { key: 'contact.form.submit_label', label: 'Submit Button Label', type: 'text', default: 'Send Message' },
      { key: 'contact.form.loading_label', label: 'Submit Loading Label', type: 'text', default: 'Sending...' },
      { key: 'contact.form.success_title', label: 'Success Title', type: 'text', default: 'Message Sent!' },
      { key: 'contact.form.success_body', label: 'Success Body', type: 'textarea', default: "We’ll get back to you soon." },
      { key: 'contact.form.error_text', label: 'Error Text', type: 'textarea', default: 'Something went wrong. Please try again.' },
      { key: 'contact.form.first_name.label', label: 'First Name Label', type: 'text', default: 'First Name *' },
      { key: 'contact.form.last_name.label', label: 'Last Name Label', type: 'text', default: 'Last Name *' },
      { key: 'contact.form.email.label', label: 'Email Label', type: 'text', default: 'Email *' },
      { key: 'contact.form.phone.label', label: 'Phone Label', type: 'text', default: 'Phone' },
      { key: 'contact.form.message.label', label: 'Message Label', type: 'text', default: 'Message *' },
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy Policy',
    fields: [
      { key: 'privacy.title', label: 'Page Title', type: 'text', default: 'Privacy Policy' },
      { key: 'privacy.updated', label: 'Last Updated', type: 'text', default: 'Last updated: January 2026' },
      {
        key: 'privacy.body_html',
        label: 'Policy Body (HTML)',
        type: 'rich',
        default:
          '<h2>Information We Collect</h2><p>When you visit BLVD Park or use our website, we may collect information you provide directly, such as your name, email address, and phone number when making reservations or signing up for events.</p><h2>How We Use Your Information</h2><p>We use the information we collect to:</p><ul><li>Process your reservations and bookings</li><li>Send you updates about events and promotions</li><li>Improve our services and customer experience</li><li>Respond to your inquiries and requests</li></ul><h2>Data Security</h2><p>We implement appropriate security measures to protect your personal information. However, no method of transmission over the internet is 100% secure.</p><h2>Contact Us</h2><p>If you have questions about this Privacy Policy, please contact us at:</p><p>BLVD Park<br/>1119 W 20th Street<br/>Houston, TX 77008</p>',
      },
    ],
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    fields: [
      { key: 'terms.title', label: 'Page Title', type: 'text', default: 'Terms of Service' },
      { key: 'terms.updated', label: 'Last Updated', type: 'text', default: 'Last updated: January 2026' },
      {
        key: 'terms.body_html',
        label: 'Terms Body (HTML)',
        type: 'rich',
        default:
          '<h2>Acceptance of Terms</h2><p>By accessing and using the BLVD Park website and services, you accept and agree to be bound by these Terms of Service.</p><h2>Use of Services</h2><p>Our services include table reservations, event bookings, and access to our facilities. You agree to use these services responsibly and in compliance with all applicable laws.</p><h2>Reservations &amp; Cancellations</h2><p>Reservations are subject to availability. We reserve the right to cancel or modify reservations with reasonable notice. For large party bookings, please contact us directly for our cancellation policy.</p><h2>Venue Rules</h2><ul><li>Guests must be 21+ to consume alcohol</li><li>Appropriate attire required</li><li>Management reserves the right to refuse service</li><li>Pickleball courts are first-come, first-served</li></ul><h2>Limitation of Liability</h2><p>BLVD Park shall not be liable for any indirect, incidental, or consequential damages arising from your use of our services or facilities.</p><h2>Contact Us</h2><p>For questions about these Terms, please contact us at:</p><p>BLVD Park<br/>1119 W 20th Street<br/>Houston, TX 77008</p>',
      },
    ],
  },
  {
    id: 'meta.home',
    title: 'Meta - Home',
    fields: [
      { key: 'meta.home.title', label: 'Home Meta Title', type: 'text', default: "BLVD Park | The Heights' Playground" },
      {
        key: 'meta.home.description',
        label: 'Home Meta Description',
        type: 'textarea',
        default: "The Heights' premier sports bar with free pickleball courts. Craft cocktails, game day vibes, and a vibrant atmosphere.",
      },
      { key: 'meta.home.image', label: 'Home Meta Image', type: 'image', default: '/images/hero-background.webp' },
    ],
  },
  {
    id: 'meta.menu.main',
    title: 'Meta - Menu (Main)',
    fields: [
      { key: 'meta.menu.main.title', label: 'Menu Meta Title', type: 'text', default: 'Menu | BLVD Park' },
      {
        key: 'meta.menu.main.description',
        label: 'Menu Meta Description',
        type: 'textarea',
        default: 'Chef-driven bites and craft cocktails at BLVD Park in the Heights.',
      },
      { key: 'meta.menu.main.image', label: 'Menu Meta Image', type: 'image', default: '/images/hero-background.webp' },
    ],
  },
  {
    id: 'meta.menu.lunch',
    title: 'Meta - Menu (Lunch)',
    fields: [
      { key: 'meta.menu.lunch.title', label: 'Lunch Meta Title', type: 'text', default: 'Lunch Menu | BLVD Park' },
      {
        key: 'meta.menu.lunch.description',
        label: 'Lunch Meta Description',
        type: 'textarea',
        default: 'Lunch specials at BLVD Park. Available Monday-Friday, 11am-3pm.',
      },
      { key: 'meta.menu.lunch.image', label: 'Lunch Meta Image', type: 'image', default: '/images/hero-background.webp' },
    ],
  },
  {
    id: 'meta.book',
    title: 'Meta - Book',
    fields: [
      { key: 'meta.book.title', label: 'Book Meta Title', type: 'text', default: 'Reserve | BLVD Park' },
      {
        key: 'meta.book.description',
        label: 'Book Meta Description',
        type: 'textarea',
        default: 'Reserve a table or book your private event at BLVD Park in the Heights.',
      },
      { key: 'meta.book.image', label: 'Book Meta Image', type: 'image', default: '/images/hero-background.webp' },
    ],
  },
  {
    id: 'meta.contact',
    title: 'Meta - Contact',
    fields: [
      { key: 'meta.contact.title', label: 'Contact Meta Title', type: 'text', default: 'Contact | BLVD Park' },
      {
        key: 'meta.contact.description',
        label: 'Contact Meta Description',
        type: 'textarea',
        default: 'Contact BLVD Park in the Heights.',
      },
      { key: 'meta.contact.image', label: 'Contact Meta Image', type: 'image', default: '/images/hero-background.webp' },
    ],
  },
  {
    id: 'meta.privacy',
    title: 'Meta - Privacy',
    fields: [
      { key: 'meta.privacy.title', label: 'Privacy Meta Title', type: 'text', default: 'Privacy Policy | BLVD Park' },
      {
        key: 'meta.privacy.description',
        label: 'Privacy Meta Description',
        type: 'textarea',
        default: 'Privacy Policy for BLVD Park',
      },
      { key: 'meta.privacy.image', label: 'Privacy Meta Image', type: 'image', default: '/images/hero-background.webp' },
    ],
  },
  {
    id: 'meta.terms',
    title: 'Meta - Terms',
    fields: [
      { key: 'meta.terms.title', label: 'Terms Meta Title', type: 'text', default: 'Terms of Service | BLVD Park' },
      {
        key: 'meta.terms.description',
        label: 'Terms Meta Description',
        type: 'textarea',
        default: 'Terms of Service for BLVD Park',
      },
      { key: 'meta.terms.image', label: 'Terms Meta Image', type: 'image', default: '/images/hero-background.webp' },
    ],
  },
];

const buildDefaultContent = () => {
  const defaults = {};
  contentSchema.forEach((section) => {
    section.fields.forEach((field) => {
      defaults[field.key] = field.default ?? '';
    });
  });
  return defaults;
};

module.exports = {
  contentSchema,
  buildDefaultContent,
};
